# .github/workflows/fullstack-ci-dependabot.yml
name: CI for Fullstack Project with Dependabot

on:
  # workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - synchronize
      - reopened

jobs:
  backend:
    name: Build and Test Backend
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.event_name == 'push'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build and Test Backend with Maven
      working-directory: ./backend
      run: mvn clean verify

    - name: Archive Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: backend-test-results
        path: backend/target/surefire-reports

  frontend:
    name: Build and Test Frontend
    runs-on: ubuntu-latest
    needs: backend  # Aguarda o job backend ser concluído
    if: github.actor == 'dependabot[bot]' || github.event_name == 'push'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Altere para a versão Node desejada

    - name: Install Dependencies
      working-directory: ./frontend
      run: npm install

    - name: Run Frontend Tests
      working-directory: ./frontend
      run: npm test -- --watchAll=false

    - name: Build Frontend
      working-directory: ./frontend
      run: npm run build

    - name: Archive Build Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: frontend-build
        path: frontend/build

  approve_and_merge:
    name: Approve and Auto-Merge Dependabot PRs
    runs-on: ubuntu-latest
    needs: [backend, frontend]  # Aguarda jobs backend e frontend concluírem
    if: github.actor == 'dependabot[bot]' # Apenas PRs do Dependabot

    steps:
    - name: Approve PR
      if: success()
      run: gh pr review ${{ github.event.pull_request.number }} --approve
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Auto-merge Dependabot PR
      if: success()
      uses: actions/github-script@v6
      with:
        script: |
          const pull_request = context.payload.pull_request;
          if (pull_request.user.login === "dependabot[bot]" && pull_request.labels.some(label => label.name === "dependencies")) {
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pull_request.number,
              merge_method: "squash" # Método de merge: "squash", "rebase" ou "merge"
            });
          }
